# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: What is time?
email: whatistime2018@gmail.com
description: I seek to uncover the ontology of time. I seek to derive time, not define it. I seek to escape relativism!

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://whatisti.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Seeker_of_Time
github_username:  what-is-time

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-analytics

disquss:
  shortname: what-is-time

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-125057367-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
